{"name": "test_create_product_with_invalid_name", "status": "broken", "statusDetails": {"message": "TypeError: SqliteProductsTable.create_product() got an unexpected keyword argument 'name'", "trace": "products_table = <dbs.sqlite_products_table.SqliteProductsTable object at 0x103ecc860>\n\n    def test_create_product_with_invalid_name(products_table):\n        # Negative test: Attempt to create a product with an invalid name\n    \n        # Get the initial count of products in the table\n        initial_product_count = len(products_table.get_all_products())\n    \n        # Attempt to create a product with an empty name\n>       empty_name_result = products_table.create_product(name=\"\")\n\ntest_get_products.py:79: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nargs = (<dbs.sqlite_products_table.SqliteProductsTable object at 0x103ecc860>,)\nkwargs = {'name': ''}, cursor = <sqlite3.Cursor object at 0x103f2f940>\n\n    def wrapper(*args, **kwargs):\n        with SqliteConnector() as cursor:\n>           return cursor.execute(fn(*args, **kwargs)).fetchall()\nE           TypeError: SqliteProductsTable.create_product() got an unexpected keyword argument 'name'\n\n../../dbs/db_base/base_sqlite_table.py:8: TypeError"}, "start": 1712649101876, "stop": 1712649101880, "uuid": "313f1b94-d968-4008-9067-553f54900dcc", "historyId": "3f14b72d0855cb47ac05141679c782c7", "testCaseId": "3f14b72d0855cb47ac05141679c782c7", "fullName": "test.db_tests.test_get_products#test_create_product_with_invalid_name", "labels": [{"name": "parentSuite", "value": "test.db_tests"}, {"name": "suite", "value": "test_get_products"}, {"name": "host", "value": "Dariias-MacBook-Pro.local"}, {"name": "thread", "value": "17978-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.db_tests.test_get_products"}]}