{"name": "test_delete_product_with_invalid_id", "status": "failed", "statusDetails": {"message": "Failed: Expected exception was not raised", "trace": "products_table = <dbs.sqlite_products_table.SqliteProductsTable object at 0x118333320>\n\n    def test_delete_product_with_invalid_id(products_table):\n        # Negative test: Attempt to delete a product with an invalid ID\n    \n        # Invalid product ID (non-existent)\n        invalid_product_id = -1\n    \n        # Get the initial count of products in the table\n        initial_product_count = len(products_table.get_all_products())\n    \n        # Attempt to delete the product with the invalid ID\n        try:\n            products_table.delete_product_by_id(invalid_product_id)\n        except Exception as exc:\n            # Check if the exception message indicates that the product ID was not found\n            assert \"Product ID not found\" in str(exc)\n        else:\n            # If no exception was raised, fail the test\n>           pytest.fail(\"Expected exception was not raised\")\nE           Failed: Expected exception was not raised\n\ntest_get_products.py:74: Failed"}, "start": 1712611484446, "stop": 1712611484448, "uuid": "6e0aa505-ce19-45cb-a1a5-b9b835893be6", "historyId": "0e2b0779f7c39af8dad96a4fbc340434", "testCaseId": "0e2b0779f7c39af8dad96a4fbc340434", "fullName": "test.db_tests.test_get_products#test_delete_product_with_invalid_id", "labels": [{"name": "parentSuite", "value": "test.db_tests"}, {"name": "suite", "value": "test_get_products"}, {"name": "host", "value": "dariias-mbp.home"}, {"name": "thread", "value": "15120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.db_tests.test_get_products"}]}